#pragma once

// This file is generated by GenerateCPP.rb

#include <vector>
#include <cstdint>

namespace Fallout1::RE::Addresses {
    std::vector<uintptr_t> module_base = {0x400000};
    std::vector<uintptr_t> player_object = {0x105734};
    std::vector<uintptr_t> player_name = {0x16bf1c};
    std::vector<uintptr_t> player_age = {0x1076c8};
    std::vector<uintptr_t> player_stats = {0x8ed34, 0x1c};
    std::vector<uintptr_t> player_xp = {0x265224};
    std::vector<uintptr_t> map_current_name = {0x2302f4};
}
