-- This file is generated by GenerateLua.rb

local addresses = {}
addresses.module_base = {0x400000}
addresses.player_object = {0x105734}
addresses.player_name = {0x16bf1c}
addresses.player_age = {0x1076c8}
addresses.player_stats = {0x8ed34, 0x1c}
addresses.player_xp = {0x265224}
addresses.map_current_name = {0x2302f4}
return addresses
