require "yaml"

working_directory   = ARGV.first
addresses_yaml_file = "GOG.yaml"
output_cpp_file     = File.join File.dirname(working_directory), "Libraries", "Cpp", "Fallout1", "include", "Fallout1", "RE", "Addresses.h"

addresses = YAML.load_file File.join(working_directory, addresses_yaml_file)

cpp = <<-CPP
#pragma once

// This file is generated by GenerateCPP.rb

#include <vector>
#include <cstdint>

namespace Fallout1::RE::Addresses {
CPP

addresses.each do |name, address|
    cpp += "    std::vector<uintptr_t> #{name} = {" + address.map { |a| "0x#{a.to_s(16)}" }.join(", ") + "};\n"
end

cpp += "}\n"

File.write output_cpp_file, cpp

# puts cpp

puts "Done! Wrote #{addresses.length} addresses to #{output_cpp_file}"
